version: '2'

services:
  weather-cities:
  # Set environment variables from this file
    env_file:
      - .env

    # Overwrite any env var defined in .env file (if required)
    environment:
      - DB_NAME=test
      - DB_PORT=5432
      - DB_HOST=postgres
      - DB_USERNAME=test
      - DB_PASSWORD=challenge
      - APP_PORT=8080

    build:
      context: .
    
    volumes:
      - .:/usr/app
      - /usr/app/node_modules/

    # Expose ports [HOST:CONTAINER}
    ports:
      - "8080:8080"

    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: "postgres:9.4.11"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=challenge
  
